### ISSUE TITLE
this is so beautiful -- Thanks a bunch! and a little question

### ISSUE THREAD

**Issue by yarikoptic** [marcindulak/vagrant-lustre-tutorial-centos6#2]
I need to troubleshoot some failures under lustre (http://git-annex.branchable.com/bugs/git-annex_doesn__39__t_work_on_lustre:_waitToSetLock:_unsupported_operation___40__Function_not_implemented__41__/) so was looking for a quick way to get a 'demo system' -- your Vagrantfile worked out beautifully (did ubuntu12 instead of centos)!!!   Thank you a lot.  
The only remaining question for me remains is how to enable some kind of user management since vagrant  user doesn't have access to /lustre (and my problem doesn't reveal itself under root).  Would you be so kind to kick me in the right direction?

Thank you in advance!

**Comment by marcindulak** [comment]
In order to use a lustre mount on a client, the given user must be present on both the client
and mds (with matching uid/gid). Different Vagrant boxes differ wrt. to vagrant uid/gid, so just use the same box as the one used for mds (centos6)::

```
$ vagrant ssh centos6 -c "sudo su -c 'mkdir /lustre/vagrant'"
$ vagrant ssh centos6 -c "sudo su -c 'chown vagrant.vagrant /lustre/vagrant'"
$ vagrant ssh centos6 -c "sudo su - vagrant -c 'touch /lustre/vagrant/testfile'"
```
