### ISSUE TITLE
error while installing lustre-osd-zfs rpm package

### ISSUE THREAD

**Issue by AshishPurkar** [marcindulak/vagrant-lustre-tutorial-centos6#3]
It's faling for me with this error
==> mds01: ---> Package lustre-osd-zfs.x86_64 0:2.8.0-2.6.32_573.12.1.el6_lustre.x86_64 will be installed
==> mds01: --> Processing Dependency: zfs-kmod for package: lustre-osd-zfs-2.8.0-2.6.32_573.12.1.el6_lustre.x86_64.x86_64
==> mds01: ---> Package lustre-osd-zfs-mount.x86_64 0:2.8.0-2.6.32_573.12.1.el6_lustre.x86_64 will be installed
==> mds01: --> Processing Dependency: libzfs.so.2()(64bit) for package: lustre-osd-zfs-mount-2.8.0-2.6.32_573.12.1.el6_lustre.x86_64.x86_64
==> mds01: --> Finished Dependency Resolution
==> mds01: Error: Package: lustre-osd-zfs-2.8.0-2.6.32_573.12.1.el6_lustre.x86_64.x86_64 (lustre-server)
==> mds01:            Requires: zfs-kmod
==> mds01: Error: Package: lustre-osd-zfs-mount-2.8.0-2.6.32_573.12.1.el6_lustre.x86_64.x86_64 (lustre-server)
==> mds01:            Requires: libzfs.so.2()(64bit)
==> mds01:  You could try using --skip-broken to work around the problem
==> mds01:  You could try running: rpm -Va --nofiles --nodigest
The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.

**Comment by ddzialak** [comment]
I've hit the same problem....

**Comment by marcindulak** [comment]
I think I run into something similar and added archive.zfsonlinux.org yum repo in fe37f8d4adc64886ad11ee5206c579d645c19437 , but now lustre is not trying to pull anything related to zfs for me. Is the error reproducible? Anyway what does `yum repolist` show on the failed mds01?

**Comment by ddzialak** [comment]
I've added archive.zfsonlinux.org (actually I've installed zfs-release-1-4.el6.noarch, which add repo) but after that: 

14:36:44     lustre-server-centos6: Running: inline script
14:36:44 ==> lustre-server-centos6: Failed to initialize ZFS library
14:36:44 ==> lustre-server-centos6: 
14:36:44 ==> lustre-server-centos6:    Permanent disk data:
14:36:44 ==> lustre-server-centos6: Target:     MGS
14:36:44 ==> lustre-server-centos6: Index:      unassigned
14:36:44 ==> lustre-server-centos6: Lustre FS:  testfs
14:36:44 ==> lustre-server-centos6: Mount type: ldiskfs
14:36:44 ==> lustre-server-centos6: Flags:      0x64
14:36:44 ==> lustre-server-centos6:               (MGS first_time update )
14:36:44 ==> lustre-server-centos6: Persistent mount opts: user_xattr,errors=remount-ro
14:36:44 ==> lustre-server-centos6: Parameters:
14:36:44 ==> lustre-server-centos6: 
14:36:44 ==> lustre-server-centos6: device size = 64MB
14:36:44 ==> lustre-server-centos6: 
14:36:44 ==> lustre-server-centos6: mkfs.lustre FATAL: "-O quota" must be supported by e2fsprogs, please upgrade your e2fsprogs.
14:36:44 ==> lustre-server-centos6: 
14:36:44 ==> lustre-server-centos6: mkfs.lustre FATAL: mkfs failed 22
14:36:44 ==> lustre-server-centos6: mkfs.lustre: exiting with 22 (Invalid argument)

I will try to upgrade...

**Comment by ddzialak** [comment]
lustre-server-centos6: https://downloads.hpdd.intel.com/public/e2fsprogs/latest/el6/RPMS/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

So I've changed baseurl (removed RPMS): 
baseurl=https://downloads.hpdd.intel.com/public/e2fsprogs/latest/el$releasever/

anyway it did not help:

```
==> lustre-server-centos6: Adding versionlock on: 0:e2fsprogs-libs-1.41.12-21.el6
...
    lustre-server-centos6: Running: inline script
==> lustre-server-centos6: Failed to initialize ZFS library
==> lustre-server-centos6: 
==> lustre-server-centos6:    Permanent disk data:
==> lustre-server-centos6: Target:     MGS
==> lustre-server-centos6: Index:      unassigned
==> lustre-server-centos6: Lustre FS:  testfs
==> lustre-server-centos6: Mount type: ldiskfs
==> lustre-server-centos6: Flags:      0x64
==> lustre-server-centos6:               (MGS first_time update )
==> lustre-server-centos6: Persistent mount opts: user_xattr,errors=remount-ro
==> lustre-server-centos6: Parameters:
==> lustre-server-centos6: 
==> lustre-server-centos6: device size = 64MB
==> lustre-server-centos6: 
==> lustre-server-centos6: mkfs.lustre FATAL: "-O quota" must be supported by e2fsprogs, please upgrade your e2fsprogs.
==> lustre-server-centos6: 
==> lustre-server-centos6: mkfs.lustre FATAL: mkfs failed 22
==> lustre-server-centos6: mkfs.lustre: exiting with 22 (Invalid argument)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

After upgrading e2fsprogs to version from RPMS directory still have problem:

```
[vagrant@lustre ~]$ rpm -qa | grep e2fsprogs
e2fsprogs-libs-1.42.13.wc5-7.el6.x86_64
e2fsprogs-1.42.13.wc5-7.el6.x86_64

[vagrant@lustre ~]$ sudo mke2fs -j -b 4096 -L MGS  -q -O uninit_bg,dir_nlink,quota,huge_file,flex_bg -E lazy_journal_init -F /dev/sdb 16384
/dev/sdb contains a ext4 file system labelled 'MGS'
    created on Fri May 20 11:31:18 2016
[vagrant@lustre ~]$ sudo mount /dev/sdb /media/xxx
mount: wrong fs type, bad option, bad superblock on /dev/sdb,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail  or so

[vagrant@lustre ~]$ dmesg | grep sdb
sd 0:0:1:0: [sdb] 131072 512-byte logical blocks: (67.1 MB/64.0 MiB)
sd 0:0:1:0: [sdb] Write Protect is off
sd 0:0:1:0: [sdb] Mode Sense: 00 3a 00 00
sd 0:0:1:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
 sdb: unknown partition table
sd 0:0:1:0: [sdb] Attached SCSI disk
EXT4-fs (sdb): couldn't mount RDWR because of unsupported optional features (100)

```

**Comment by ddzialak** [comment]
Instead of installing the newest version of lustre server, I'm installing version 2.7.0 and it seems to working again:

```
 [lustre-server]
 name=CentOS-$releasever - Lustre server
-baseurl=https://downloads.hpdd.intel.com/public/lustre/latest-feature-release/el$releasever/server/
+#baseurl=https://downloads.hpdd.intel.com/public/lustre/latest-feature-release/el$releasever/server/
+baseurl=https://downloads.hpdd.intel.com/public/lustre/lustre-2.7.0/el$releasever/server/
```

**Comment by marcindulak** [comment]
After `vagrant destroy -f` try to perform a clean up following https://github.com/marcindulak/vagrant-lustre-tutorial-centos6/blob/master/README.md .  "==> lustre-server-centos6:" is not part of https://github.com/marcindulak/vagrant-lustre-tutorial-centos6/blob/master/Vagrantfile and my experience with Lustre is such that you try different combinations of various components until Lustre seems operational and freeze all of them. Incremental changes on a live system will almost certainly lead to problems. If the problem is still there please open a new bug and mention the commit hash.

**Comment by FayeG** [comment]
Hi, I ran into the "Requires: libzfs.so.2()(64bit)" problem today on RHEL 7.2.
Do we have a workaround?

**Comment by ddzialak** [comment]
I'm using version 2.7.0 (because I don't need the latest release) and it's working fine:

```
 [lustre-server]
 name=CentOS-$releasever - Lustre server
-baseurl=https://downloads.hpdd.intel.com/public/lustre/latest-feature-release/el$releasever/server/
+#baseurl=https://downloads.hpdd.intel.com/public/lustre/latest-feature-release/el$releasever/server/
+baseurl=https://downloads.hpdd.intel.com/public/lustre/lustre-2.7.0/el$releasever/server/

...

 [lustre-client]
 name=CentOS-$releasever - Lustre client
-baseurl=https://downloads.hpdd.intel.com/public/lustre/latest-feature-release/el$releasever/client/
+baseurl=https://downloads.hpdd.intel.com/public/lustre/lustre-2.7.0/el$releasever/client/
```

**Comment by marcindulak** [comment]
It's a question of ordering packages given to yum install.
Lustre-2.8.0 installs on el6 correctly for ldiskfs with:

```
 yum -y install lustre-osd-ldiskfs* lustre e2fsprogs* lustre-tests
```

and for zfs with:

```
 yum -y install lustre-osd-zfs* lustre e2fsprogs* lustre-tests
```

As mentioned at https://lists.01.org/pipermail/hpdd-discuss/2016-June/002998.html
one needs to explicitly pull lustre-osd-\* and the order of packages given to yum matters.

$ git rev-parse HEAD
30c282f9f8cb296138876ec8407ec03a827d85f0
$ vagrant up mds01 | egrep 'osd|e2fsprogs'
...
==> mds01:   e2fsprogs-debuginfo.x86_64 0:1.42.13.wc5-7.el6
==> mds01:   e2fsprogs-devel.x86_64 0:1.42.13.wc5-7.el6
==> mds01:   e2fsprogs-static.x86_64 0:1.42.13.wc5-7.el6
==> mds01:   lustre-osd-ldiskfs.x86_64 0:2.8.0-2.6.32_573.12.1.el6_lustre.x86_64
==> mds01:   lustre-osd-ldiskfs-mount.x86_64 0:2.8.0-2.6.32_573.12.1.el6_lustre.x86_64
==> mds01:   e2fsprogs.x86_64 0:1.42.13.wc5-7.el6
==> mds01:   e2fsprogs-libs.x86_64 0:1.42.13.wc5-7.el6
...
$ vagrant ssh mds01 -c 'which lctl'
/usr/sbin/lctl
$ vagrant ssh mds01 -c 'rpm -qf `which lctl`'
lustre-2.8.0-2.6.32_573.12.1.el6_lustre.x86_64.x86_64

**Comment by FayeG** [comment]
Hi,

Yeah. We eventually figured this out. The trick was how to tell puppet this. In the end we did this:

ensure_packages(
        ['lustre-osd-ldiskfs', ‘kernel-2.6.32-504.8.1.el6_lustre.x86_64’],
        {
          before => Package['lustre'],
        }
      )
ensure_packages(['lustre'])

And that seems to have settled matters and I hope this note gets googled by the next person whom encounters this ☺

Faye
